plugins {
    id "java"
	 //id "edu.wpi.first.GradleRIO" version "2022.4.1"
}

sourceCompatibility = JavaVersion.VERSION_26
targetCompatibility = JavaVersion.VERSION_26

deploy {
	targets {
		/*roborio(getTargetTypeClass('RoboRIO')) {
			team = project.frc.getTeamNumber()
			debug = project.frc.getDebugOrdefault(false)

			artifacts {
				frcJava(getArtifactTypeClass('FRCJavaArtifact')) {
				}

				frcStaticFileDeploy(getArtifactTypeClass('FileTreeArtifact')) {
					files = project.fileTree('src/main/deploy')
					directory = '/home/lvuser/deploy'
				}
			}
		}*/
	}
}

def deployArtifact = deploy.targets.roborio.artifacts.frcJava

wpi.java.debugJni = false

def includeDesktopSupport = false

dependencies {}

wpi.sim.addGui().defaultEnabled = true
wpi.sim.addDriverstation()

jar {
	from {
		configurations.runtimeClasspath.collect {
			it.isDirectory() ? it : zipTree(it)
		}
	}

	manifest edu.wpi.first.gralerio.GradleRIOPlugin.javaManifest(ROBOT_MAIN_CLASS)

	duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

deployArtifact.jarTask = jar
wpi.java.configureExecutableTasks(jar)
wpi.java.configureTestTasks(test)
