// gradle's configuration is absolutely indecipherable.
// doesn't help that WPI writes comments that don't help, in first person 

plugins {
    id "java"
    id "edu.wpi.first.GradleRIO" version "2026.2.1"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

def ROBOT_MAIN_CLASS = "org.team4153.biocore.Main"

// Define my targets (RoboRIO) and artifacts (deployable files)
// This is added by GradleRIO's backing project DeployUtils.
deploy {
    targets {
        roborio(getTargetTypeClass('RoboRIO')) {
            // Team number is loaded either from the .wpilib/wpilib_preferences.json
            // or from command line. If not found an exception will be thrown.
            // You can use getTeamOrDefault(team) instead of getTeamNumber if you
            // want to store a team number in this file.
            team = project.frc.getTeamNumber()
            debug = project.frc.getDebugOrDefault(false)

            artifacts {
                // First part is artifact name, 2nd is artifact type
                // getTargetTypeClass is a shortcut to get the class type using a string

                frcJava(getArtifactTypeClass('FRCJavaArtifact')) {
                }

                // Static files artifact
                frcStaticFileDeploy(getArtifactTypeClass('FileTreeArtifact')) {
                    files = project.fileTree('src/main/deploy')
                    directory = '/home/lvuser/deploy'
                    deleteOldFiles = false // Change to true to delete files on roboRIO that no
                                           // longer exist in deploy directory of this project
                }
            }
        }
    }
}

def deployArtifact = deploy.targets.roborio.artifacts.frcJava

// Set to true to use debug for all targets including JNI, which will drastically impact
// performance.
wpi.java.debugJni = false

// Set this to true to enable desktop support.
def includeDesktopSupport = true

// Defining my dependencies. In this case, WPILib (+ friends), and vendor libraries.
// Also defines JUnit 5.
dependencies {
    annotationProcessor wpi.java.deps.wpilibAnnotations()
    implementation wpi.java.deps.wpilib()
    implementation wpi.java.vendor.java()

    roborioDebug wpi.java.deps.wpilibJniDebug(wpi.platforms.roborio)
    roborioDebug wpi.java.vendor.jniDebug(wpi.platforms.roborio)

    roborioRelease wpi.java.deps.wpilibJniRelease(wpi.platforms.roborio)
    roborioRelease wpi.java.vendor.jniRelease(wpi.platforms.roborio)

    nativeDebug wpi.java.deps.wpilibJniDebug(wpi.platforms.desktop)
    nativeDebug wpi.java.vendor.jniDebug(wpi.platforms.desktop)
    simulationDebug wpi.sim.enableDebug()

    nativeRelease wpi.java.deps.wpilibJniRelease(wpi.platforms.desktop)
    nativeRelease wpi.java.vendor.jniRelease(wpi.platforms.desktop)
    simulationRelease wpi.sim.enableRelease()

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	
	 implementation("com.typesafe:config:1.4.3")
}

test {
    useJUnitPlatform()
    systemProperty 'junit.jupiter.extensions.autodetection.enabled', 'true'
}

// Simulation configuration (e.g. environment variables).
wpi.sim.addGui().defaultEnabled = true
wpi.sim.addDriverstation()

// Setting up my Jar File. In this case, adding all libraries into the main jar ('fat jar')
// in order to make them all available at runtime. Also adding the manifest so WPILib
// knows where to look for our Robot Class.
jar {
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    from('src') { into 'backup/src' }
    from('vendordeps') { into 'backup/vendordeps' }
    from('build.gradle') { into 'backup' }
    manifest edu.wpi.first.gradlerio.GradleRIOPlugin.javaManifest(ROBOT_MAIN_CLASS)
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

// Configure jar and deploy tasks
deployArtifact.jarTask = jar
wpi.java.configureExecutableTasks(jar)
wpi.java.configureTestTasks(test)


tasks.withType(JavaCompile) {
    options.compilerArgs.addAll([
	 	'-XDstringConcat=inline',   // "foo" + "bar" is "foobar" after compile
		'-deprecation',
		'-Werror',                  // warnings suck.
		"-Xlint:unchecked"
	 ])
}


/* I absolutely despise the src/main/java/com/example/... project structure.
 * Like... the com/example directories are doing literally nothing.
 * Why the [explative] is it there???
 * Oh you want to manually add the sources of another library?
 * MAKE ANOTHER SUBPROJECT OR ONE FOLDER.
 * src/ tells you where the sources are and you can do stuff like src-core and src-main
 * main/ separates code from tests and you can have main-native or main-jvm for java native compilation
 * java/ tells you the language and if there is binary incompatibility you can do java-25, java-8, java-17, etc
 * but com/example?
 * there is no use for it!!!
 * holy moly, the code in a repository from our organization has the package start with our organization?
 * impossible, i could never have figured that out without com/example.
 *
 * If you hate it so much, then just tell gradle and vscode to ignore it.
 * I TRIED. I TRIED FOR 4 HOURS.
 * EVERY SINGLE TIME IT COMPLETELY STRIPS THE 'org.team4153' FROM THE RUNTIME CLASS.
 * IT THROWS 'java.lang.ClassNotFoundException: org.team4153.biocore.Main'
 * IT FAILS TO RESOLVE AN IMPORT
 * I HATE THIS BUILD TOOL
 * I HATE IDES
 * I HATE JAVA
 * GET ME OUT OF HERE
 * I wish to program in Scala with SBT, but nooo.
 * "scala is too complicated"
 * "we're gonna make the only build tool compatible with WPILib the worst one ever"
 * I really really really want to like the JVM.
 * The JVM is honestly such a cool system and I love it.
 * but this...
 *
 * Tl;dr com/example at the end is useless, stop using it or I will find you.
*/