can: [
	{
		id = 1001
		name = "drivetrain front-left drive"
		type = "motor"
		class = "sparkmax"
		nodeId = 1
		canBus = 0
		brake = true
		currentLimit = 40
	}
	{
		id = 1002
		name = "drivetrain front-left steer"
		type = "motor"
		class = "sparkmax"
		nodeId = 2
		canBus = 0
		brake = true
		currentLimit = 40
		feedback = "AbsoluteEncoder"
		encoderOffset = 1.2345
	}
	# ....
]

input: [
	{
		port = 0
		deadband = 0.05
		type = "controller"
		class = "xbox"
	}
]

shape {
	width = 0.82
	length = 0.75
}

logging {
	mode = "match" # "match", "pit", "dev" in order of increasing logging
	file = "none"  # "none" or a file path to log to
}
