motors: [
	{
		canId = 0
		id = 0
		name = "drivetrain front-left drive"
		type = SparkMAX
	}
	{
		canId = 1
		id = 1
		name = "drivetrain front-left turn"
		type = SparkMAX
		encoderOffset = 0.42
	}
	{
		canId = 2
		id = 2
		name = "drivetrain front-right drive"
		type = SparkMAX
	}
	{
		canId = 3
		id = 3
		name = "drivetrain front-right turn"
		type = SparkMAX
		encoderOffset = 0.95
	}
]
