# This is HOCON (https://github.com/lightbend/config)
# comments can be #, //, and /* */

# CAN hardware elements
can: [
	{
		id = 1001
		name = "drivetrain front-left drive"
		type = "motor"
		class = "sparkmax"
		nodeId = 0
		canPort = 0
		brake = true
	}
	{
		id = 1002
		name = "drivetrain front-left steer"
		type = "motor"
		class = "sparkmax"
		nodeId = 1
		canPort = 0
		brake = true
		feedback = "AbsoluteEncoder"
		encoderOffset = 1.2345
	}
	{
		id = 1003
		name = "drivetrain front-right drive"
		type = "motor"
		class = "sparkmax"
		nodeId = 2
		canPort = 0
		brake = true
	}
	{
		id = 1004
		name = "drivetrain front-right steer"
		type = "motor"
		class = "sparkmax"
		nodeId = 3
		canPort = 0
		brake = true
		feedback = "AbsoluteEncoder"
		encoderOffset = 1.2345
	}
	{
		id = 1005
		name = "drivetrain back-left drive"
		type = "motor"
		class = "sparkmax"
		nodeId = 4
		canPort = 0
		brake = true
	}
	{
		id = 1006
		name = "drivetrain back-left steer"
		type = "motor"
		class = "sparkmax"
		nodeId = 5
		canPort = 0
		brake = true
		feedback = "AbsoluteEncoder"
		encoderOffset = 1.2345
	}
	{
		id = 1007
		name = "drivetrain back-right drive"
		type = "motor"
		class = "sparkmax"
		nodeId = 6
		canPort = 0
		brake = true
	}
	{
		id = 1008
		name = "drivetrain back-right steer"
		type = "motor"
		class = "sparkmax"
		nodeId = 7
		canPort = 0
		brake = true
		feedback = "AbsoluteEncoder"
		encoderOffset = 1.2345
	}
]


# non-CAN input hardware such as the controller
input: [
	{
		id = 1
		port = 0
		deadband = 0.05
		type = "controller"
		class = "xbox"
	}
]


# use internal ids to refer to everything
drivetrain {
	type = "swerve"
	class = "default"
	maxSpeedMPS = 6.8
	front-left {
		power = 1001
		steer = 1002
	}
	front-right {
		power = 1003
		steer = 1004
	}
	back-left {
		power = 1005
		steer = 1006
	}
	back-right {
		power = 1007
		steer = 1008
	}
}


# logging utilities. generally you want to log less during matches to reduce
# the ammount of packets between the robot and driver station
logging {
	mode = "dev" # "match", "pit", "dev" in order of increasing logging
	file = "none"  # "none" or a file path to log to
}


# you also can just add whatever you want to save to this config file. For
# example, physical dimensions:
shape {
	width = 0.8382  # 33 inches as meters
	length = 0.6858 # 27 inches as meters
}
